import json

from agents.models.config import PLAYLIST_SEED
from agents.models.models import SharedAgentState
from agents.services.spotify_service import (
    get_spotify_client,
    create_playlist,
    add_tracks_to_playlist,
)
from uagents import Agent, Context

playlist_agent = Agent(
    name="playlist",
    seed=PLAYLIST_SEED,
    port=8008,
    mailbox=True,
    publish_agent_details=True,
)

PLAYLIST_NAMES = {
    "chill": {
        "studying": "Late Night Study Session",
        "working": "Deep Focus Flow",
        "driving": "Cruisin' Easy",
        "sleeping": "Drift Off",
        "cooking": "Kitchen Chill",
        "hanging out": "Lowkey Hangs",
        "listening": "Chill Vibes",
    },
    "hype": {
        "working out": "Beast Mode",
        "party": "Turn Up",
        "driving": "Pedal to the Metal",
        "hanging out": "Squad Energy",
        "listening": "Hype Mix",
    },
    "sad": {
        "listening": "In My Feelings",
        "driving": "Rainy Drive",
    },
    "happy": {
        "listening": "Good Vibes Only",
        "driving": "Sunshine Drive",
        "hanging out": "Feel Good Hangs",
    },
    "focus": {
        "studying": "Lock In",
        "working": "Grind Mode",
        "listening": "Deep Focus",
    },
    "energetic": {
        "working out": "Sweat Session",
        "listening": "Energy Boost",
    },
    "romantic": {
        "listening": "Date Night",
    },
    "angry": {
        "listening": "Rage Fuel",
        "working out": "Fury Mode",
    },
}


def get_playlist_name(mood: str, activity: str) -> str:
    mood_names = PLAYLIST_NAMES.get(mood, {})
    name = mood_names.get(activity)
    if name:
        return name
    name = mood_names.get("listening")
    if name:
        return name
    return f"{mood.title()} {activity.title()} Mix"


def playlist_workflow(state: SharedAgentState) -> SharedAgentState:
    data = json.loads(state.pipeline_data)
    context = data.get("context", {})
    taste = data.get("taste_profile", {})
    recommendations = data.get("recommendations", [])

    mood = context.get("mood", "chill")
    activity = context.get("activity", "listening")
    playlist_name = get_playlist_name(mood, activity)

    # Try to create the playlist on Spotify
    spotify_url = None
    track_uris = [t["uri"] for t in recommendations if "uri" in t]

    print(f"[DEBUG] Track URIs ({len(track_uris)}): {track_uris[:3]}...")
    print(f"[DEBUG] Playlist name: {playlist_name}")

    if track_uris:
        try:
            sp = get_spotify_client(user_address=state.user_sender_address)
            print(f"[DEBUG] Spotify client: {'OK' if sp else 'None'}")
            if sp:
                # Verify token scopes
                user = sp.current_user()
                print(f"[DEBUG] Authenticated as: {user['id']}")

                summary = taste.get("summary", "")
                description = f"Generated by Playlist Curator • {mood} • {activity}"
                if summary:
                    description += f" • {summary}"

                print(f"[DEBUG] Creating playlist '{playlist_name}' for user '{user['id']}'...")
                playlist_id = create_playlist(sp, playlist_name, description)
                print(f"[DEBUG] Playlist created: {playlist_id}")
                add_tracks_to_playlist(sp, playlist_id, track_uris)
                print(f"[DEBUG] Added {len(track_uris)} tracks")
                spotify_url = f"https://open.spotify.com/playlist/{playlist_id}"
        except Exception as e:
            print(f"[DEBUG] Failed to create Spotify playlist: {type(e).__name__}: {e}")

    # Build the formatted output
    lines = [f"🎵 {playlist_name}"]
    lines.append(f"{len(recommendations)} tracks • {mood} • {activity}")
    lines.append("")

    for i, track in enumerate(recommendations, 1):
        lines.append(f"{i}. \"{track['title']}\" — {track['artist']}")

    summary = taste.get("summary", "")
    if summary:
        lines.append("")
        lines.append(f"Based on your taste: {summary}")

    if spotify_url:
        lines.append("")
        lines.append(f"✅ Playlist created on your Spotify: {spotify_url}")

    state.result = "\n".join(lines)
    state.pipeline_stage = "done"
    return state


@playlist_agent.on_message(SharedAgentState)
async def handle_message(ctx: Context, sender: str, state: SharedAgentState):
    ctx.logger.info(
        f"Received state from orchestrator: session={state.chat_session_id}, query={state.query!r}"
    )
    state = playlist_workflow(state)
    ctx.logger.info(f"Playlist formatted, sending back to orchestrator")
    await ctx.send(sender, state)


if __name__ == "__main__":
    playlist_agent.run()
