# Fallback song pool used when Spotify API is unavailable
MOCK_SONGS = [
    {"title": "The Less I Know The Better", "artist": "Tame Impala", "album": "Currents"},
    {"title": "Redbone", "artist": "Childish Gambino", "album": "Awaken, My Love!"},
    {"title": "Nights", "artist": "Frank Ocean", "album": "Blonde"},
    {"title": "HUMBLE.", "artist": "Kendrick Lamar", "album": "DAMN."},
    {"title": "Snooze", "artist": "SZA", "album": "SOS"},
    {"title": "Pink + White", "artist": "Frank Ocean", "album": "Blonde"},
    {"title": "Money Trees", "artist": "Kendrick Lamar", "album": "good kid, m.A.A.d city"},
    {"title": "Do I Wanna Know?", "artist": "Arctic Monkeys", "album": "AM"},
    {"title": "Passionfruit", "artist": "Drake", "album": "More Life"},
    {"title": "Blinding Lights", "artist": "The Weeknd", "album": "After Hours"},
    {"title": "Ivy", "artist": "Frank Ocean", "album": "Blonde"},
    {"title": "Sweater Weather", "artist": "The Neighbourhood", "album": "I Love You."},
    {"title": "Star Shopping", "artist": "Lil Peep", "album": "crybaby"},
    {"title": "505", "artist": "Arctic Monkeys", "album": "Favourite Worst Nightmare"},
    {"title": "Borderline", "artist": "Tame Impala", "album": "The Slow Rush"},
    {"title": "Die For You", "artist": "The Weeknd", "album": "Starboy"},
    {"title": "Sicko Mode", "artist": "Travis Scott", "album": "Astroworld"},
    {"title": "Nikes", "artist": "Frank Ocean", "album": "Blonde"},
    {"title": "Slide", "artist": "Calvin Harris", "album": "Funk Wav Bounces Vol. 1"},
    {"title": "Location", "artist": "Playboi Carti", "album": "Playboi Carti"},
    {"title": "Ghost", "artist": "Deftones", "album": "Koi No Yokan"},
    {"title": "Digital Bath", "artist": "Deftones", "album": "White Pony"},
    {"title": "Gassed Up", "artist": "Loathe", "album": "I Let It in and It Took Everything"},
    {"title": "Two-Headed Boy", "artist": "Neutral Milk Hotel", "album": "In the Aeroplane Over the Sea"},
    {"title": "Skinny", "artist": "Billie Eilish", "album": "HIT ME HARD AND SOFT"},
    {"title": "Luther", "artist": "Kendrick Lamar", "album": "GNX"},
    {"title": "Kyoto", "artist": "Phoebe Bridgers", "album": "Punisher"},
    {"title": "Bags", "artist": "Clairo", "album": "Immunity"},
    {"title": "Motion Sickness", "artist": "Phoebe Bridgers", "album": "Stranger in the Alps"},
    {"title": "Kerala", "artist": "Bonobo", "album": "Migration"},
]
