orchestrator:
	python -m agents.orchestrator.orchestrator_fetchai_wrapped_agent

spotify:
	python -m agents.spotify.spotify_fetchai_wrapped_agent

taste:
	python -m agents.taste.taste_fetchai_wrapped_agent

context:
	python -m agents.context.context_fetchai_wrapped_agent

discovery:
	python -m agents.discovery.discovery_fetchai_wrapped_agent

playlist:
	python -m agents.playlist.playlist_fetchai_wrapped_agent
